name: Validator

on: [push, pull_request]

jobs:
	build:
		runs-on: ubuntu-latest
		steps:
		- uses: actions/checkout@v2
		- name: HTML5Validator
			uses: Cyb3r-Jak3/html5validator-action
			with:
				root: .
