name: Build

on: push

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: npm ci
      - name: Build Electron app
        run: ./buildall.sh "${{ runner.os }}"
        shell: bash
      - uses: actions/upload-artifact@v2
        with:
          name: ${{ runner.os }}-build
          path: build-${{ runner.os }}-x64